### ISSUE TITLE
Using AdminUtils breaks the build

### ISSUE THREAD

**Issue by lukasz-szewc** [asmaier/mini-kafka#1]
This commit 8616352 breaks build - and test fail. (At least on windows machine.)
Before that commit - works fine.

**Comment by asmaier** [comment]
I just tried it, and it works fine on my machine (Mac OS X 10.11) :-/

But to fix the test can you try to change the timeout in the line 94 of KafkaProducerIT.java `ConsumerRecords<Integer, byte[]> records = consumer.poll(1000);`
from 1000 back to 3000 and see if the test runs on your machine?

**Comment by lukasz-szewc** [comment]
It seems that timeout is causing problems. (at least for me). If I give 3000 works fine.

**Comment by asmaier** [comment]
I increased now the timeout of the consumer to 3 seconds. This should fix this issue. Thank you for reporting it.
