### ISSUE TITLE
This code is not working with kafka version 0.11.0.2

### ISSUE THREAD

**Issue by dhruv-bansal** [asmaier/mini-kafka#2]
Can you please provide the code sample for Kafka version 0.11.0.2. This code is not working. 
May you tell any references how to approach?

**Comment by asmaier** [comment]
What is the error message you get? Does it not compile? Do you need 0.11.0.2 specifically, because the newest version of Kafka is now 1.0 (https://www.confluent.io/blog/apache-kafka-goes-1-0/). But I didn't have time to look into it, yet.

**Comment by dhruv-bansal** [comment]
yes, for now, I need specifically for version 0.11.02. Could you help, please? Or give me a hint of approach I would dig more myself. I have looked into the Kafka code for hint of what exception I am getting but no success yet
I am getting following exception:

00:09:06.112 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0x5 zxid:0x4 txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NoNode for /brokers
00:09:06.119 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0xb zxid:0x8 txntype:-1 reqpath:n/a Error Path:/config Error:KeeperErrorCode = NoNode for /config
00:09:06.126 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0x13 zxid:0xd txntype:-1 reqpath:n/a Error Path:/admin Error:KeeperErrorCode = NoNode for /admin
00:09:06.183 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0x1d zxid:0x13 txntype:-1 reqpath:n/a Error Path:/cluster Error:KeeperErrorCode = NoNode for /cluster
00:09:06.539 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:setData cxid:0x27 zxid:0x17 txntype:-1 reqpath:n/a Error Path:/controller_epoch Error:KeeperErrorCode = NoNode for /controller_epoch
00:09:06.684 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:delete cxid:0x3c zxid:0x1a txntype:-1 reqpath:n/a Error Path:/admin/preferred_replica_election Error:KeeperErrorCode = NoNode for /admin/preferred_replica_election
00:09:06.770 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0x46 zxid:0x1b txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NodeExists for /brokers
00:09:06.770 [ProcessThread(sid:0 cport:50192):] INFO org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1603c92dae80001 type:create cxid:0x47 zxid:0x1c txntype:-1 reqpath:n/a Error Path:/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids

**Comment by asmaier** [comment]
I couldn't reproduce your specific error message. But I upgraded the code to work with Kafka 0.11.0.2. It runs (at least on my machine). Maybe it helps.
